/*  pages/index/login  登录界面  */
/*  pages/index/index  主菜单  */
/*  pages/physicianvisits/physicianvisitsList  问诊列表  */
/*  pages/my/index  我的  */
/*  pages/my/mydoctor  我的医生  */
/*  pages/my/myorder  我的订单  */
/*  pages/my/mymedicalrecords  我的病历  */
/*  pages/my/myprofile  完善资料  */
/*  pages/my/addregion  新增收货地址   */
/*  pages/my/mycoupons  我的优惠券   */
/*  pages/my/couponsList  我的失效优惠券  */
/*  pages/my/aboutus  关于我们  */
/*  pages/my/aboutusdetails  关于我们详情  */
/*  pages/my/preliminarydatadetails  我的病例-查看问诊资料  */
/*  pages/doctor/doctordetails  医生详情  */
/*  pages/doctor/purchasingservicedetails  购买服务详情  */
/*  pages/order/orderdetails  订单详情  */
/*  pages/order/physicianorderdetails  问诊订单详情  */
/*  pages/order/prescriptionorderdetails  药方订单详情  */
/*  pages/makemedicine/index  取药列表  */
/*  pages/makemedicine/makemedicinedetails  取药详情  */
/*  pages/upload/one  上传病例第一步  */
/*  pages/upload/two  上传病例第二步  */
/*  pages/upload/three  上传病例第三步  */
/*  pages/upload/four  上传病例第四步  */
/*  pages/im/index  im窗口  */
/*  pages/problemfeedback/index  问题反馈  */
/*  template/doctordetails  医生详情公共模块  */
/*  template/physicianorderdetails  问诊订单详情公共模块  */
/*  template/prescriptionorderdetails  药方订单详情公共模块  */
/*  template/purchasingservicedetails  购买服务详情公共模块  */
/*  template/mymedicalrecords  我的病例公共模块  */
